### ISSUE TITLE
Does not build on OpenBSD 7.2

### ISSUE THREAD

**Issue by jtbx** [wahern/cqueues#254]
When I build cqueues via `luarocks-5.3 install cqueues` and `make` on OpenBSD, it fails to compile:
```
/tmp/luarocks_cqueues-20200726.53-0-rAyaSK/cqueues-rel-20200726/src/lib/socket.c:188:12: error: incomplete definition of type 'struct ssl_st'
        return ssl->server != NULL;
               ~~~^
/usr/include/openssl/ossl_typ.h:160:16: note: forward declaration of 'struct ssl_st'
typedef struct ssl_st SSL;
               ^
/tmp/luarocks_cqueues-20200726.53-0-rAyaSK/cqueues-rel-20200726/src/lib/socket.c:2543:19: error: variable has incomplete type 'BIO_METHOD' (aka 'struct bio_method_st')
static BIO_METHOD bio_methods = {
                  ^
/usr/include/openssl/bio.h:283:16: note: forward declaration of 'struct bio_method_st'
typedef struct bio_method_st BIO_METHOD;
               ^
2 errors generated.
gmake: *** [/tmp/luarocks_cqueues-20200726.53-0-rAyaSK/cqueues-rel-20200726/src/lib/GNUmakefile:39: /tmp/luarocks_cqueues-20200726.53-0-rAyaSK/cqueues-rel-20200726/src/lib/socket.o] Error 1

Error: Build error: Failed building.
```

Is there a method to build cqueues properly on OpenBSD?
