### ISSUE TITLE
Does not build on OpenBSD 7.6

### ISSUE THREAD

**Issue by U-9200** [wahern/cqueues#260]
Hi!

I'm referencing and quoting the following issue: https://github.com/wahern/cqueues/issues/254

> When I build cqueues via luarocks-5.3 install cqueues and make on OpenBSD, it fails to compile:
> 
> ```
> cc -O2 -std=gnu99 -fPIC -g -Wall -Wextra -Wno-missing-field-initializers -Wno-initializer-overrides -Wno-unused -Wno-dollar-in-identifier-extension -O2 -fPIC -DLUA_COMPAT_APIINTCASTS -I/usr/local/include/lua-5.4 -I"/usr/include" -I"/usr/include" -DCOMPAT53_PREFIX=cqueues -DCQUEUES_VENDOR='"quae@daurnimator.com"' -DCQUEUES_VERSION=20200726L  -c -o /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/5.4/dns.o /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/dns.c
> cp /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/config.h /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/config.h
> cc -O2 -std=gnu99 -fPIC -g -Wall -Wextra -Wno-missing-field-initializers -Wno-initializer-overrides -Wno-unused -Wno-dollar-in-identifier-extension -O2 -fPIC -I"/usr/include" -I"/usr/include" -DSOCKET_DEBUG -DHAVE_CONFIG_H -DDNS_RANDOM=arc4random -c -o /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/socket.o /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/socket.c
> /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/socket.c:188:12: error: incomplete definition of type 'struct ssl_st'
>         return ssl->server != NULL;
>                ~~~^
> /usr/include/openssl/ossl_typ.h:150:16: note: forward declaration of 'struct ssl_st'
> typedef struct ssl_st SSL;
>                ^
> /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/socket.c:2543:19: error: variable has incomplete type 'BIO_METHOD' (aka 'struct bio_method_st')
> static BIO_METHOD bio_methods = {
>                   ^
> /usr/include/openssl/bio.h:283:16: note: forward declaration of 'struct bio_method_st'
> typedef struct bio_method_st BIO_METHOD;
>                ^
> 2 errors generated.
> gmake: *** [/tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/GNUmakefile:39: /tmp/luarocks_cqueues-20200726.54-0-5123961/cqueues-rel-20200726/src/lib/socket.o] Fehler 1
> 
> Error: Build error: Failed building.
> ```
> 
> Is there a method to build cqueues properly on OpenBSD?

I have the same problem and am unsure how to solve this?

Can you possibly give an advice?

Thank you in advance :-)
