### PR TITLE
src/lib/socket.c: fix build with libressl >= 3.5.0

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with libressl >= 3.5.0:

```
/nvmedata/autobuild/instance-26/output-1/build/lua-cqueues-20200726/src/lib/socket.c: In function 'compat_SSL_is_server':
/nvmedata/autobuild/instance-26/output-1/build/lua-cqueues-20200726/src/lib/socket.c:188:12: error: invalid use of incomplete typedef 'SSL' {aka 'struct ssl_st'}
  188 |  return ssl->server != NULL;
      |            ^~
/nvmedata/autobuild/instance-26/output-1/build/lua-cqueues-20200726/src/lib/socket.c: At top level:
/nvmedata/autobuild/instance-26/output-1/build/lua-cqueues-20200726/src/lib/socket.c:2543:1: error: variable 'bio_methods' has initializer but incomplete type
 2543 | static BIO_METHOD bio_methods = {
      | ^~~~~~
```

Fixes:
 - http://autobuild.buildroot.org/results/823c9e27cdb8e01a048cb751287c01c5dc70f860

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

File: src/lib/socket.c [hunk 1]
```diff
@@ -2580,7 +2582,9 @@ static void bio_methods_init(void) {
 
 static BIO_METHOD *so_get_bio_methods() {
 	if (bio_methods == NULL) {
+#ifndef LIBRESSL_VERSION_NUMBER
```
Comment (daurnimator) [inline src/lib/socket.c:2585]: What libressl feature is this checking for?

It should be more explicit.

File: src/lib/socket.c [hunk 2]
```diff
@@ -135,7 +135,7 @@ int socket_v_api(void) {
 #endif
 
 #ifndef HAVE_SSL_IS_SERVER
-#define HAVE_SSL_IS_SERVER OPENSSL_PREREQ(1,1,0)
+#define HAVE_SSL_IS_SERVER (OPENSSL_PREREQ(1,1,0) || LIBRESSL_PREREQ(3,5,0))
```
Comment (daurnimator) [inline src/lib/socket.c:138]: This was added in https://github.com/libressl/openbsd/commit/27c7f5cbee077ba1c2cb41736dde99a00c116b9f

Which was present in libressl 2.7.0.

**Comment by daurnimator** [comment]
I'm committing the fixes (minus the CRYPTO_ONCE polyfill) now.

@mischief something like your fix might work; I don't love the exact form though. Send it as a PR and we can iterate a bit
